version: 2
updates:
  - package-ecosystem: npm, bundler, composer, maven, mix, cargo, gradle, nuget, gomod, docker, elm, gitsubmodule, github-actions, pip, terraform, pub
    directory: "/"
    schedule:
      interval: "weekly"
